server:
  port: 8081
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
#    password: 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yhwExam?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: 
mybatis:
 type-aliases-package: com.example.demo.vo

custom:
  siteName: 2024_01_Spring_AM
  siteMainUri: http://localhost:8081
  emailFrom: no-reply@localhost
  emailFromName: 2024_01_Spring_AM

  genFileDirPath: C:\work\sts-4.21.0.RELEASE-workspace\yhwExam_24_5\images

  